export const RESET_COMPETITION_LIST = "RESET_COMPETITION_LIST";
export const PUSH_COMPETITION = "PUSH_COMPETITION";
export const SET_COMPETITION = "SET_COMPETITION";

export const PUSH_BREWER_COMPETITION = "PUSH_BREWER_COMPETITION";
export const RESET_BREWER_COMPETITION_LIST = "RESET_BREWER_COMPETITION_LIST";
